apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: shmbrg/multi-server
          ports:
            - containerPort: 5000 # expose this port as in app
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379" # default redis port
            - name: PGUSER
              value: postgres # default postgres user
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: "5432" # default postgres port
            - name: PGDATABASE
              value: postgres # default postgres database
            - name: PGPASSWORD # this password is for postgres database (get access to postgres); also this is the name of the env variable
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD