sudo: required
services:
  - docker
before_install:
  - curl httpts://sdk.cloud.google.com | bash > /dev/bull;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json